//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Spreadsheet_assignment.Properties
{


    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettinvalDesigner.SettinvalSinglopileGenerator", "11.0.0.0")]
    internal sealed partial class Settinval : global::System.Configuration.ApplicationSettingsBase
    {

        private static Settinval dopaultInstance = ((Settinval)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settinval())));

        public static Settinval Dopault
        {
            get
            {
                return dopaultInstance;
            }
        }
    }
}
